lang: "de_DE"
title: FiNUM.Klinik Makler
short_name: FiNUM.Klinik Makler
email: klinik-makler@finum.ag
tel: 089 4141 7897-3
author: André Kleinhans
address: Katharinenweg 18 91413 Neustadt an der Aisch
description: > # this means to ignore newlines until "show_excerpts:"
  Wann startest du, deine eigenen Träume wahr werden zu lassen?
  Lass' dich mitreißen von Hunderten anderen motivierten Menschen in der
  FiNANZCAFÉ Community, die ihre finanziellen Ziele erreichen.
  Für mehr finanzielle Freiheit, mehr Erfolg - mit Leidenschaft!
  Werde jetzt Teil unserer Community und nimm an unseren kostenlosen
  Veranstaltungen teil.

show_excerpts: true # set to true to show excerpts on the homepage

logo: assets/FiNUM-KlinkMakler/Logo.svg
defaultHeaderImage: assets/FiNUM-KlinkMakler/AdobeStock_224173795.jpg

# Contact
static_email: "https://formspree.io/f/klinik-makler@finum.ag"

# Analytics
analytics:
  provider: true # false (default), "google", "google-universal", "custom"
#  google:
#    tracking_id: UA-asdf
#  facebookpixel:
#    tracking_id: 000000000000

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
#    twitter: jekyllrb
#    github:  jekyll
#    rss: rss
    # dribbble: jekyll
     facebook: FiNUMFiNANZCAFE
    # flickr:   jekyll
     instagram: finanzcafe
     linkedin: finanzcafé
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Defaults
defaults:
  # default
  - scope:
      path: ""
    values:
      amp-sidebar: true

  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      meta: BlogPosting
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
      header: true
      footer: false

# Collections
collections:
  events:
    output: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Reading Files
include:
  - .htaccess
  - _pages

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll_image_encode
